name       : libsndfile
version    : 1.0.30
release    : 18
source     :
    - https://github.com/erikd/libsndfile/archive/v1.0.30.tar.gz : 5942b963d1db3ed8ab1ffb85708322aa9637df76d9fe84e1dfe49a97a90e8f47
homepage   : http://www.mega-nerd.com/libsndfile
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Read/write file library containing sampled sound
description: |
    Libsndfile is a C library for reading and writing files containing sampled sound through one standard library interface
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(flac)
    - pkgconfig32(ogg)
    - pkgconfig32(opus)
    - pkgconfig32(sqlite3)
    - pkgconfig32(vorbis)
    - autogen-32bit
setup      : |
    %autogen --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
