name       : libsndfile
version    : 1.0.28
release    : 16
source     :
    - http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz : 1ff33929f042fa333aed1e8923aa628c3ee9e1eb85512686c55092d1e5a9dfa9
homepage   : http://www.mega-nerd.com/libsndfile
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Read/write file library containing sampled sound
description: |
    Libsndfile is a C library for reading and writing files containing sampled sound through one standard library interface
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(flac)
    - pkgconfig32(ogg)
    - pkgconfig32(sqlite3)
    - pkgconfig32(vorbis)
setup      : |
    %apply_patches
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
