name       : libsndfile
version    : 1.0.26
release    : 8
source     :
    - http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz : cd6520ec763d1a45573885ecb1f8e4e42505ac12180268482a44b28484a25092
homepage   : http://www.mega-nerd.com/libsndfile
license    :
    - LGPL-2.1
component  : multimedia.library
summary    : Read/write file library containing sampled sound
builddeps  :
    - pkgconfig(vorbis)
    - pkgconfig32(vorbis)
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
    - pkgconfig(flac)
    - pkgconfig32(flac)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(sqlite3)
    - pkgconfig32(sqlite3)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Libsndfile is a C library for reading and writing files containing sampled sound through one standard library interface
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
