name       : libsndfile
version    : 1.2.0
release    : 24
source     :
    - https://github.com/libsndfile/libsndfile/archive/refs/tags/1.2.0.tar.gz : 62dc4e2bcd45f6f0e89cbc3522cc90eb174dca0eef0a0d19ead289833b390cd7
homepage   : http://www.mega-nerd.com/libsndfile
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Read/write file library containing sampled sound
description: |
    Libsndfile is a C library for reading and writing files containing sampled sound through one standard library interface
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(flac)
    - pkgconfig32(ogg)
    - pkgconfig32(opus)
    - pkgconfig32(sqlite3)
    - pkgconfig32(vorbis)
    - autogen-32bit
patterns   :
    - 32bit-devel : /usr/lib32/cmake/*
setup      : |
    %patch -p1 < $pkgfiles/0001-Handle-absolute-install-paths.patch
    %cmake_ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
