name       : libsndfile
version    : 1.0.31
release    : 19
source     :
    - https://github.com/libsndfile/libsndfile/archive/refs/tags/1.0.31.tar.gz : 8cdee0acb06bb0a3c1a6ca524575643df8b1f3a55a0893b4dd9f829d08263785
homepage   : http://www.mega-nerd.com/libsndfile
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Read/write file library containing sampled sound
description: |
    Libsndfile is a C library for reading and writing files containing sampled sound through one standard library interface
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(flac)
    - pkgconfig32(ogg)
    - pkgconfig32(opus)
    - pkgconfig32(sqlite3)
    - pkgconfig32(vorbis)
    - autogen-32bit
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
